### ISSUE TITLE
Cant verify the hash values from original spec

### ISSUE THREAD

**Issue by dcwatson84** [rapidhashing/cryptonight#2]
When I try to verify the hash values from the original spec (https://cryptonote.org/cns/cns008.txt)

"This is a test"
a084f01d1437a09c6985401b60d43554ae105802c5f5d8a9b3253649c0be6605

I get different a value:
93b90fab55adf4e98787d33a38e71106e8c016f1a124dfc784f3cca4d938b1af

Am I doing something wrong? Or are the original examples out-dated? How can I verify the algorithm against a current implementation?

**Comment by mattcode55** [comment]
>Am I doing something wrong?

I'm not sure, I tried "This is a test" with/without the null terminator, with `\n`, `\r\n` etc and couldn't get the same hash.

---

>How can I verify the algorithm against a current implementation?

You can call Monero's own `cn_fast_hash` yourself. I tested it like this:

**CMakeLists.txt**
```cmake
set(hashtest_sources
  hashtest.cpp)

set(hashtest_headers)

set(hashtest_private_headers)

monero_private_headers(hashtest
  ${hashtest_private_headers})
monero_add_executable(hashtest
  ${hashtest_sources}
  ${hashtest_headers}
  ${hashtest_private_headers})
target_link_libraries(hashtest
  PRIVATE
    cncrypto
    common)
add_dependencies(hashtest
  version)
set_property(TARGET hashtest
  PROPERTY
    OUTPUT_NAME "hashtest")
install(TARGETS hashtest DESTINATION bin)
```

**hashtest.cpp**
```c++
#include <iomanip>
#include <stdio.h>

#include "crypto/crypto.h"
#include "crypto/hash.h"

int main() {
	crypto::hash x = crypto::cn_fast_hash("\x01", 1);
	for (int i = 0; i < 32; i++)
		printf("%02x", x.data[i] & 0xFF);
	printf("\n");
}
```

Which outputted `5fe7f977e71dba2ea1a68e21057beebb9be2ac30c6410aa38d4f3fbe41dcffd2`.

The following Java code outputted the same thing:

**Test.java**
```java
package net.rapidhashing.cryptonight;

public class Test {
	public static void main(String[] args) {
		byte[] in = new byte[] { 0x01 };
		byte[] out = new byte[32];
		Cryptonight.fastHash(in, out);

		for (int i = 0; i < out.length; i++)
			System.out.printf("%02x", out[i]);

		System.out.println();
	}
}
```

---

>Or are the original examples out-dated?

Possibly, I haven't looked into it too much. If you figure out why the hashes in CNS008 are different to what we get, please let me know.

**Comment by dcwatson84** [comment]
Looks good. As long as it produces the same thing as the Monero source then the CNS008 investigation is purely academic. Thanks for the info!

**Comment by m3gagluk** [comment]
"93b90fab55adf4e98787d33a38e71106e8c016f1a124dfc784f3cca4d938b1af" is a Keccak-1600 of "This is a test", which is only a first step of a hash operation.
